IF
	InParty("C0NIRIK")
	OR(2)
	Global("C0NPCInterjectTimer","MYAREA",0)
	!RealGlobalTimerExpired("C0NPCInterjectTimer","MYAREA")
	CombatCounter(0)
	Switch("C0NirikTL1","MYAREA")
THEN
RESPONSE #0
	SetGlobal("C0NirikTL1","MYAREA",1)
	RealSetGlobalTimer("C0NPCInterjectTimer","MYAREA",2)
RESPONSE #1
	SetGlobal("C0NirikTL1","MYAREA",2)
	DisplayStringHead("C0NIRIK",~For Kuldahar, the North, and the fallen... I'll see this through to the end.~)
	RealSetGlobalTimer("C0NPCInterjectTimer","MYAREA",2)
END